services:
  - type: web
    name: Post-summerizer
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.enableCORS=false
    # envVars:
    #   - key: PYTHON_VERSION
    #     value: 3.10
    #   - key: GROQ_API_KEY
    #     value: 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  # Or leave blank and set in dashboard
